---
MEDIA_CORE_VERIFICATION_STATUSES:
  -
    :description: "<%= I18n.t(:'statuses.media.undetermined.description') %>"
    :id: undetermined
    :label: "<%= I18n.t(:'statuses.media.undetermined.label') %>"
    :style:
  -
    :description: "<%= I18n.t(:'statuses.media.not_applicable.description') %>"
    :id: not_applicable
    :label: "<%= I18n.t(:'statuses.media.not_applicable.label') %>"
    :style:
  -
    :description: "<%= I18n.t(:'statuses.media.in_progress.description') %>"
    :id: in_progress
    :label: "<%= I18n.t(:'statuses.media.in_progress.label') %>"
    :style:
  -
    :description: "<%= I18n.t(:'statuses.media.not_true.description') %>"
    :id: "false"
    :label: "<%= I18n.t(:'statuses.media.not_true.label') %>"
    :style:
  -
    :description: "<%= I18n.t(:'statuses.media.verified.description') %>"
    :id: verified
    :label: "<%= I18n.t(:'statuses.media.verified.label') %>"
    :style:
SOURCE_CORE_VERIFICATION_STATUSES:
  -
    :description: "<%= I18n.t(:'statuses.source.undetermined.description') %>"
    :id: undetermined
    :label: "<%= I18n.t(:'statuses.source.undetermined.label') %>"
    :style:
  -
    :description: "<%= I18n.t(:'statuses.source.credible.description') %>"
    :id: credible
    :label: "<%= I18n.t(:'statuses.source.credible.label') %>"
    :style:
  -
    :description: "<%= I18n.t(:'statuses.source.not_credible.description') %>"
    :id: not_credible
    :label: "<%= I18n.t(:'statuses.source.not_credible.label') %>"
    :style:
  -
    :description: "<%= I18n.t(:'statuses.source.slightly_credible.description') %>"
    :id: slightly_credible
    :label: "<%= I18n.t(:'statuses.source.slightly_credible.label') %>"
    :style:
  -
    :description: "<%= I18n.t(:'statuses.source.sockpuppet.description') %>"
    :id: sockpuppet
    :label: "<%= I18n.t(:'statuses.source.sockpuppet.label') %>"
    :style:
