version: '2'
services:

  redis:
    image: redis
    ports:
      - 127.0.0.1:6379:6379
        
  elasticsearch:
    image: meedan/elasticsearch
    ports:
      - 127.0.0.1:9200:9200
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
